### ISSUE TITLE
If collapsed, expand on new received message

### ISSUE THREAD

**Issue by MattCowski** [irontec/angular-bootstrap-simple-chat#3]
Hopefully I'll have time to add this functionality within the next few days. I'll try to submit a PR

**Comment by MattCowski** [comment]
Cool, this works. Place inside the directive's controller:
(coffeescript)

```
    $scope.$watchCollection 'messages', (newVal, oldVal)->
      return if (newVal.length <= 0)
      toggle() if isHidden
```

**Comment by khaled4vokalz** [comment]
@MattCowski  can you please share Javascript of those lines.... Coffeescript is not something for me... : (
