### ISSUE TITLE
ChatBox

### ISSUE THREAD

**Issue by YnievesDotNet** [irontec/angular-bootstrap-simple-chat#7]
Hello, How I can doit an PopupBox with this chat?

Thanks.

**Comment by aitorllj93** [comment]
Hi! I' have posted two popup style samples at [samples/popup.html](https://github.com/irontec/angular-bootstrap-simple-chat/blob/master/sample/popup.html)

I don't know what type of popup do you mean so I made one with Bootstrap's Modal and other with JS window.open. Check them out and reopen this issue if you have any problem :)

**Comment by YnievesDotNet** [comment]
Similar at facebook chatbox.

It s possible.

Thanks.
