### ISSUE TITLE
Grunt/Bower (wiredep) is removing source and css from index.html

### ISSUE THREAD

**Issue by cash1981** [irontec/angular-bootstrap-simple-chat#9]
Look at this:
http://stackoverflow.com/questions/32895341/grunt-is-removing-scripts-and-css-in-index-html/32962802#32962802

I believe you need to update your bower.json to match the new spec

**Comment by zxl9171** [comment]
I think in the bower.json, it should be

```
 "main": [
    "src/scripts/index.js",
    "src/css/style.js"
  ],
```

rather than

```
 "main": [
    "src/scripts/",
    "src/css/"
  ],
```
